### ISSUE TITLE
eroro with this song https://www.youtube.com/watch?v=xIGhbkEG_tw

### ISSUE THREAD

**Issue by KARONAGAMING** [unburn/musicard#13]
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'width')
      at musicCard.build (/home/container/node_modules/musicard/build/structures/musicCard.js:229:59)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async module.exports.run (/home/container/src/events/poruEvents/player/trackStart.js:36:46)
} reason: TypeError: Cannot read properties of undefined (reading 'width')
    at musicCard.build (/home/container/node_modules/musicard/build/structures/musicCard.js:229:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports.run (/home/container/src/events/poruEvents/player/trackStart.js:36:46)

**Comment by UnschooledGamer** [comment]
> Unhandled Rejection at: Promise {
>   <rejected> TypeError: Cannot read properties of undefined (reading 'width')
>       at musicCard.build (/home/container/node_modules/musicard/build/structures/musicCard.js:229:59)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async module.exports.run (/home/container/src/events/poruEvents/player/trackStart.js:36:46)
> } reason: TypeError: Cannot read properties of undefined (reading 'width')
>     at musicCard.build (/home/container/node_modules/musicard/build/structures/musicCard.js:229:59)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async module.exports.run (/home/container/src/events/poruEvents/player/trackStart.js:36:46)

Hello, To resolve this issue I need the following details:
1. trackStart.js code
2. The imageUrl provided to musicard

**Comment by flameface** [comment]
> Unhandled Rejection at: Promise { TypeError: Cannot read properties of undefined (reading 'width') at musicCard.build (/home/container/node_modules/musicard/build/structures/musicCard.js:229:59) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async module.exports.run (/home/container/src/events/poruEvents/player/trackStart.js:36:46) } reason: TypeError: Cannot read properties of undefined (reading 'width') at musicCard.build (/home/container/node_modules/musicard/build/structures/musicCard.js:229:59) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async module.exports.run (/home/container/src/events/poruEvents/player/trackStart.js:36:46)

The image you used is low quality image that canvas can't load.
